# Generated by Django 3.1.7 on 2021-04-24 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_auto_20210424_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='category',
            field=models.CharField(choices=[('General', 'General'), ('Business', 'Business'), ('Entertainment', 'Entertainment'), ('Health', 'Health'), ('Science', 'Science'), ('Sports', 'Sports'), ('Technology', 'Technology')], default='General', max_length=25),
        ),
    ]
